# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='detail',
            field=models.TextField(verbose_name='\u54c1\u724c\u4ecb\u7ecd'),
        ),
    ]
