# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_auto_20170911_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='classify',
            field=models.ImageField(default='', upload_to='classify/%Y/%m', verbose_name='\u7cfb\u5217'),
        ),
    ]
