# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0003_brand_classify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycleclassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u54c1\u724c\u7cfb\u5217')),
                ('category', models.CharField(choices=[('dz', '\u5927\u7ec4\u8f66'), ('tt', '\u8ba1\u65f6\u8f66'), ('yy', '\u8d8a\u91ce'), ('tz', '\u94c1\u4e09'), ('xx', '\u4f11\u95f2')], max_length=5, verbose_name='\u5b9a\u4f4d')),
                ('image', models.ImageField(upload_to='RoadBicycle/%Y/%m', verbose_name='\u7cfb\u5217\u5c01\u9762\u56fe')),
                ('detail', models.TextField(max_length=300, verbose_name='\u4ecb\u7ecd')),
                ('add_time', models.TimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7cfb\u5217',
                'verbose_name_plural': '\u7cfb\u5217',
            },
        ),
        migrations.CreateModel(
            name='ClassifyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u578b\u53f7')),
                ('material', models.CharField(choices=[('tx', '\u78b3\u7ea4\u7ef4'), ('lhj', '\u94dd\u5408\u91d1'), ('gj', '\u94a2')], max_length=5, verbose_name='\u6750\u6599')),
                ('image', models.ImageField(upload_to='RoadBicyclename/%Y/%m', verbose_name='\u56fe\u7247')),
                ('detail', models.TextField(verbose_name='\u4ecb\u7ecd')),
                ('add_time', models.TimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycle.Bicycleclassify', verbose_name='\u7cfb\u5217')),
            ],
            options={
                'verbose_name': '\u578b\u53f7',
                'verbose_name_plural': '\u578b\u53f7',
            },
        ),
        migrations.RemoveField(
            model_name='roadbicycle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='classify',
        ),
        migrations.DeleteModel(
            name='RoadBicycle',
        ),
        migrations.AddField(
            model_name='bicycleclassify',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycle.Brand', verbose_name='\u54c1\u724c'),
        ),
    ]
