# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0004_auto_20170912_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifylist',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bicycle.Brand', verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='classifylist',
            name='image',
            field=models.ImageField(upload_to='RoadBicycleName/%Y/%m', verbose_name='\u56fe\u7247'),
        ),
    ]
