# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0005_auto_20170912_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifylist',
            name='price',
            field=models.CharField(default='', max_length=10, verbose_name='\u4ef7\u683c'),
        ),
    ]
