# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0006_classifylist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifylist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u578b\u53f7'),
        ),
    ]
