# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u59d3\u540d')),
                ('position', models.CharField(choices=[('gc', 'GC\u8f66\u624b'), ('fj', '\u526f\u5c06'), ('cj', '\u51b2\u523a')], max_length=5, verbose_name='\u5b9a\u4f4d')),
                ('detail', models.TextField(max_length=300, verbose_name='\u8be6\u60c5')),
                ('image', models.ImageField(upload_to='TeamMember/%Y/%m', verbose_name='\u7167\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u961f\u5458',
                'verbose_name_plural': '\u961f\u5458',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(default='', max_length=40, verbose_name='\u8f66\u961f')),
                ('detail', models.TextField(null=True, verbose_name='\u8f66\u961f\u8be6\u60c5')),
                ('image', models.ImageField(null=True, upload_to='teams/%Y/%m', verbose_name='\u8f66\u961f\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f66\u961f',
                'verbose_name_plural': '\u8f66\u961f',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams', verbose_name='\u8f66\u961f'),
        ),
    ]
