# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170911_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='detail',
            field=models.TextField(null=True, verbose_name='\u8f66\u961f\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image',
            field=models.ImageField(null=True, upload_to='teams/%Y/%m', verbose_name='\u8f66\u961f\u56fe'),
        ),
    ]
